title: '#OpenGovTech'
description: >
  Following Wuthering Bytes 2019 (Hebden Bridge)
  we are being open with gov tech.

theme: minima

defaults:
  - scope:
      path: ""
    values:
      layout: page
