title: '#OpenGovTech'
description: >
  Optimisint value with \#RadicallyOpen GovTech.

theme: minima
author: ODI Leeds

defaults:
  - scope:
      path: ""
    values:
      layout: page
  - scope:
      path: ""
      type: posts
    values:
      layout: post

permalink: /:categories/:year-:month-:day-:title/

collections:
  - assets
  - contributors
  