title: '#OpenGovTech'
description: >
  Following Wuthering Bytes 2019 (Hebden Bridge)
  we are being open with gov tech.

theme: minima
author: ODI Leeds

defaults:
  - scope:
      path: ""
    values:
      layout: page

permalink: /:categories/:year/:month/:day/:title/

collections:
  - assets
  - contributors
  