title: '#OpenGovTech'
description: >
  Following Wuthering Bytes 2019 (Hebden Bridge)
  we are being open with gov tech.

theme: minima
author: ODI Leeds

defaults:
  - scope:
      path: ""
    values:
      layout: page
  - scope:
      path: ""
      type: posts
    values:
      layout: post

permalink: /:categories/:year-:month-:day-:title/

collections:
  - assets
  - contributors
  