---
layout: raw
---
backend:
  name: github
  repo: odileeds/OpenGovTech
  base_url: https://kltfd8s7m9.execute-api.eu-west-2.amazonaws.com
  auth_endpoint: prod/auth

publish_mode: editorial_workflow
media_folder: images

collections:
{% include admin/blog.yml %}
{% include admin/blog.yml category='story' %}
{%- raw -%}
  - name: assets
    label: Assets
    label_singular: Asset
    folder: _assets
    extension: md
    slug: "{{slug}}"
    create: true
    fields:
      - name: title
        label: Title
        widget: string
      - name: originator
        widget: relation
        collection: contributors
        displayFields: title
        searchFields: title
        valueField: name
        multiple: true
      - name: external_url
        label: External URL
        widget: string
        required: false
      - name: date_added
        label: Date Added
        default: ""
        widget: datetime
        dateFormat: LL
        timeFormat: false
      - name: date_checked
        label: Date Checked
        default: ""
        widget: datetime
        dateFormat: LL
        timeFormat: false
        required: false
      - name: summary
        label: Summary
        widget: string
        required: false
      - label: Featured Image
        required: false
        name: image
        widget: image
      - name: body
        label: Body
        widget: markdown
        required: false
  - name: contributors
    label: Contributors
    label_singular: Contributor
    folder: _contributors
    create: true
    slug: '{{slug}}'
    summary: '{{title}}'
    fields:
      - { name: name, label: Identifier, widget: string }
      - { name: title, label: Name, widget: string }
      - { name: homepage, widget: string, required: false }
      - { name: logo_url, widget: string, required: false }
  - name: config
    label: Configuration
    files:
      - label: Menu
        name: menu
        file: _data/menu.yaml
        fields:
          - name: items
            widget: list
            fields:
              - name: page
                widget: select
                options: {% endraw -%}
                    {% for p in site.pages -%}
                      {% capture b %}{% if a %}{{ a }},{% endif -%}{label: '{{ p.title | default: p.path }}', value: '{{ p.path }}'}{%- endcapture %}{% assign a = b -%}
                    {% endfor -%}[{{ a }}]{%- raw -%}

  # - name: "draft" # Used in routes, e.g., /admin/collections/blog
  #   label: "Draft" # Used in the UI
  #   folder: "_drafts" # The path to the folder where the documents are stored
  #   create: true # Allow users to create new documents in this collection
  #   slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
  #   fields: # The fields for each document, usually in front matter
  #     - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
  #     - {label: "Title", name: "title", widget: "string"}
  #     - {label: "Publish Date", name: "date", widget: "datetime"}
  #     - {label: "Featured Image", name: "thumbnail", widget: "image"}
  #     - {label: "Body", name: "body", widget: "markdown"}
  # - name: "projects" # Used in routes, e.g., /admin/collections/posts
  #   label: "Projects" # Used in the UI
  #   label_singular: Project
  #   folder: "_projects" # The path to the folder where the documents are stored
  #   create: true # Allow users to create new documents in this collection
  #   slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
  #   fields: # The fields for each document, usually in front matter
  #     - label: Layout
  #       name: layout
  #       widget: hidden
  #       default: project
  #     - label: Title
  #       name: title
  #       widget: string
  #     - label: Status
  #       name: status
  #       widget: select
  #       options:
  #         - unknown
  #         - bid
  #         - won
  #         - started
  #         - completed
  #     - label: Start Date
  #       name: start_date
  #       widget: datetime
  #       default: ""
  #       required: false
  #       format: "YYYY-MM-DD"
  #     - label: End Date
  #       name: end_date
  #       widget: datetime
  #       default: ""
  #       required: false
  #       format: "YYYY-MM-DD"
  #     - label: Team Lead
  #       name: team_lead
  #       widget: relation
  #       collection: team
  #       displayFields: display_name
  #       searchFields: display_name
  #       valueField: name
  #     - label: Team
  #       name: team
  #       widget: relation
  #       collection: team
  #       displayFields: display_name
  #       searchFields: display_name
  #       valueField: name
  #       multiple: true
  #     - label: Body
  #       name: body
  #       widget: markdown
  # - name: team # Used in routes, e.g., /admin/collections/posts
  #   label: Team Members # Used in the UI
  #   label_singular: Team Member
  #   folder: _team # The path to the folder where the documents are stored
  #   create: true # Allow users to create new documents in this collection
  #   slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
  #   identifier_field: name
  #   summary: "{{display_name}}, {{role}}"
  #   fields: # The fields for each document, usually in front matter
  #     - label: Id
  #       name: name
  #       widget: string
  #     - label: Name
  #       name: display_name
  #       widget: string
  #     - label: Role
  #       name: role
  #       widget: string
  #     - label: Body
  #       name: body
  #       widget: markdown
  #       required: false
{% endraw %}